export { default as LoginForm } from './loginForm'
export { default as Nav } from './navigation'
export { default as Footer } from './footer'
export { default as YaMap } from './yaMap'
export { default as ContactsInfo } from './contactsInfo'
